# Generated by Django 4.0.3 on 2022-06-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social_icon_adding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_icon_name', models.CharField(max_length=30)),
                ('social_icon_link_except_http', models.CharField(max_length=30)),
            ],
        ),
    ]
