# Generated by Django 4.0.3 on 2022-06-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOCIAL_ICON', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social_icon_adding',
            options={'verbose_name': 'Social Icon'},
        ),
    ]
