# Generated by Django 4.0.3 on 2022-06-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOCIAL_ICON', '0002_alter_social_icon_adding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_icon_adding',
            name='social_icon_image',
            field=models.ImageField(default=None, null=True, upload_to='social_icon/'),
        ),
    ]
