# Generated by Django 4.0.3 on 2022-06-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='email_id',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='singup',
            name='firstname',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='singup',
            name='lastname',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='singup',
            name='number',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='singup',
            name='password',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
