# Generated by Django 4.0.3 on 2022-06-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0002_alter_singup_email_id_alter_singup_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singup',
            options={'verbose_name': 'User'},
        ),
    ]
