# Generated by Django 3.2.6 on 2022-07-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0003_alter_singup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='singup',
            name='forgetpass',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
