# Generated by Django 3.2.6 on 2022-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0004_singup_forgetpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='singup',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
