# Generated by Django 3.2.6 on 2022-07-30 07:46

from django.db import migrations, models
import website_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_logo', models.ImageField(upload_to='logo/', validators=[website_settings.models.validates_image])),
                ('Footer_logo', models.ImageField(upload_to='logo/', validators=[website_settings.models.validates_image20])),
            ],
        ),
    ]
