# Generated by Django 3.2.6 on 2022-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logofield',
            name='Footer_logo',
            field=models.ImageField(upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='logofield',
            name='heading_logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
