# Generated by Django 3.2.6 on 2022-07-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0002_auto_20220730_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slogan', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Website slogan',
                'verbose_name_plural': 'Website slogans',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='logofield',
            options={'managed': True, 'verbose_name': 'Logo', 'verbose_name_plural': 'Logo field'},
        ),
        migrations.AlterModelTable(
            name='logofield',
            table='',
        ),
    ]
