# Generated by Django 3.2.6 on 2022-07-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0003_auto_20220730_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slogan',
            old_name='Slogan',
            new_name='slogan',
        ),
    ]
