# Generated by Django 4.0.3 on 2022-06-28 15:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='content_des',
            field=tinymce.models.HTMLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='content_title',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
