# Generated by Django 4.0.3 on 2022-06-28 15:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0002_alter_about_us_content_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='content_des',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='content_title',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='sub_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
