# Generated by Django 4.0.3 on 2022-06-29 07:47

from django.db import migrations, models
import userinterphase.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0003_alter_about_us_content_alter_about_us_content_des_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_Name', models.CharField(max_length=255)),
                ('Banner_Image', models.ImageField(upload_to='all_banner_except_home/', validators=[userinterphase.models.validate_image], verbose_name='Banner Image (1920X464px)')),
            ],
        ),
        migrations.DeleteModel(
            name='All_banner',
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'managed': True, 'verbose_name': 'About us', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='contact_details_section',
            options={'managed': True, 'verbose_name': 'contact address', 'verbose_name_plural': 'contact address'},
        ),
        migrations.AlterModelOptions(
            name='home_carousel',
            options={'managed': True, 'verbose_name': 'Home Carousal', 'verbose_name_plural': 'Home Carousals'},
        ),
        migrations.AlterModelOptions(
            name='home_collection_banner',
            options={'managed': True, 'verbose_name': 'Home Collection Banner', 'verbose_name_plural': 'Home Collection Banners'},
        ),
        migrations.AlterModelOptions(
            name='return_refund_policy',
            options={'managed': True, 'verbose_name': 'Return and refund policie', 'verbose_name_plural': 'Return and refund policies'},
        ),
        migrations.AlterModelOptions(
            name='terms_and_condition',
            options={'managed': True, 'verbose_name': 'Terms and Condition', 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AlterModelTable(
            name='about_us',
            table='',
        ),
        migrations.AlterModelTable(
            name='contact_details_section',
            table='',
        ),
        migrations.AlterModelTable(
            name='home_carousel',
            table='',
        ),
        migrations.AlterModelTable(
            name='home_collection_banner',
            table='',
        ),
        migrations.AlterModelTable(
            name='return_refund_policy',
            table='',
        ),
        migrations.AlterModelTable(
            name='terms_and_condition',
            table='',
        ),
    ]
