# Generated by Django 4.0.3 on 2022-06-29 07:52

from django.db import migrations, models
import userinterphase.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0004_banners_delete_all_banner_alter_about_us_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='Banner_Image',
            field=models.ImageField(height_field=464, upload_to='all_banner_except_home/', validators=[userinterphase.models.validate_image], verbose_name='Banner Image (1920X464px)', width_field=1920),
        ),
    ]
