# Generated by Django 4.0.3 on 2022-06-29 07:55

from django.db import migrations, models
import userinterphase.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0005_alter_banners_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='Banner_Image',
            field=models.ImageField(upload_to='all_banner_except_home/', validators=[userinterphase.models.validate_image], verbose_name='Banner Image (1920X464px)'),
        ),
    ]
