# Generated by Django 4.0.3 on 2022-06-29 08:15

from django.db import migrations, models
import userinterphase.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0006_alter_banners_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='Banner_Image',
            field=models.ImageField(help_text='Please use our recommended dimensions: 1920 x 464 PX, 150 KB MAX', upload_to='all_banner_except_home/', validators=[userinterphase.models.validate_image], verbose_name='Banner Image (1920X464px)'),
        ),
    ]
