# Generated by Django 4.0.3 on 2022-06-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0007_alter_banners_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'managed': True, 'verbose_name': 'All Banner', 'verbose_name_plural': 'All Banners'},
        ),
        migrations.AlterField(
            model_name='banners',
            name='Banner_Name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterModelTable(
            name='banners',
            table='',
        ),
    ]
