# Generated by Django 4.0.3 on 2022-06-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0008_alter_banners_options_alter_banners_banner_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'managed': True, 'verbose_name': 'Faq', 'verbose_name_plural': 'Faqs'},
        ),
        migrations.AlterField(
            model_name='about_us',
            name='side_image',
            field=models.FileField(null=True, upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='title',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='faqs',
            table='',
        ),
    ]
