# Generated by Django 4.0.3 on 2022-06-30 06:24

from django.db import migrations, models
import tinymce.models
import userinterphase.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0009_alter_faqs_options_alter_about_us_side_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_title', models.CharField(max_length=255)),
                ('Blog_banner_Image', models.ImageField(help_text='Please use our recommended dimensions: 868x510pxPX, 150 KB MAX', upload_to='Blog_image/', validators=[userinterphase.models.validate_image], verbose_name='Blog Banner Image(868x510px)')),
                ('Blog_first_Image', models.ImageField(help_text='Please use our recommended dimensions: 8424x300pxPX, 100 KB MAX', upload_to='Blog_image/', validators=[userinterphase.models.validate_images], verbose_name='Blog Banner Image(868x510px)')),
                ('Blog_second_Image', models.ImageField(help_text='Please use our recommended dimensions: 8424x300pxPX, 100 KB MAX', upload_to='Blog_image/', validators=[userinterphase.models.validate_images], verbose_name='Blog Banner Image(868x510px)')),
                ('category', models.CharField(help_text='please mention your blog is in which category', max_length=30)),
                ('author', models.CharField(default='annynomus', help_text='please mention your name', max_length=30, null=True, verbose_name='Author name (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
