# Generated by Django 4.0.3 on 2022-06-30 06:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0011_alter_blog_blog_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Blog_title', unique=True),
        ),
    ]
