# Generated by Django 4.0.3 on 2022-07-01 18:14

from django.db import migrations, models
import userinterphase.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0012_blog_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_first_Image',
            field=models.ImageField(help_text='Please use our recommended dimensions: 424x300px, 100 KB MAX', upload_to='Blog_image/', validators=[userinterphase.models.validate_images], verbose_name='Blog first image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Blog_second_Image',
            field=models.ImageField(help_text='Please use our recommended dimensions: 424x300px, 100 KB MAX', upload_to='Blog_image/', validators=[userinterphase.models.validate_images], verbose_name='Blog second image'),
        ),
    ]
