# Generated by Django 4.0.3 on 2022-07-01 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0003_alter_singup_options'),
        ('userinterphase', '0013_alter_blog_blog_first_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogcomment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinterphase.blog')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinterphase.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_login.singup')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
