# Generated by Django 4.0.3 on 2022-07-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0016_alter_blogcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
