# Generated by Django 3.2.6 on 2022-07-10 12:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0018_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='side_image',
            field=models.FileField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='sub_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
