# Generated by Django 3.2.6 on 2022-07-20 06:34

from django.db import migrations, models
import userinterphase.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0019_auto_20220710_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_collection_banner',
            name='IMAGE_BIG_LEFT_870X800px',
            field=models.ImageField(upload_to='home/home_all_banner/', validators=[userinterphase.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='home_collection_banner',
            name='IMAGE_RIGHT_DOWN_870X390px',
            field=models.ImageField(upload_to='home/home_all_banner/', validators=[userinterphase.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='home_collection_banner',
            name='IMAGE_SMALL_FIRST_425X390px',
            field=models.ImageField(upload_to='home/home_all_banner/', validators=[userinterphase.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='home_collection_banner',
            name='IMAGE_SMALL_SECOND_425X390px',
            field=models.ImageField(upload_to='home/home_all_banner/', validators=[userinterphase.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='home_collection_banner',
            name='MIDDLE_SIDE_IMAGE_1920X1080px',
            field=models.ImageField(upload_to='home/home_all_banner/', validators=[userinterphase.models.validate_image]),
        ),
    ]
