# Generated by Django 3.2.6 on 2022-07-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0020_auto_20220720_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='Banner_Name',
            field=models.CharField(max_length=255),
        ),
    ]
