# Generated by Django 3.2.6 on 2022-07-21 09:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0021_alter_banners_banner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus_heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=30)),
                ('content', tinymce.models.HTMLField()),
                ('side_image', models.FileField(upload_to='about_us/')),
            ],
            options={
                'verbose_name': 'About us heading',
                'verbose_name_plural': 'About us headings',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'managed': True, 'verbose_name': 'About us content', 'verbose_name_plural': 'About us all content'},
        ),
        migrations.AlterField(
            model_name='about_us',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='side_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='sub_title',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
