# Generated by Django 3.2.6 on 2022-07-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0022_auto_20220721_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='content',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='side_image',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='title',
        ),
    ]
