# Generated by Django 3.2.6 on 2022-07-21 11:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0023_auto_20220721_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
