# Generated by Django 3.2.6 on 2022-07-21 12:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0024_alter_faqs_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='content_des',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='aboutus_heading',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='return_refund_policy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='terms_and_condition',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
