# Generated by Django 3.2.6 on 2022-07-21 12:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterphase', '0026_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Privacy policy',
                'verbose_name_plural': 'Privacy policies',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='return_refund_policy',
            options={'managed': True, 'verbose_name': 'Return and refund policy', 'verbose_name_plural': 'Return and refund policies'},
        ),
    ]
