# Generated by Django 3.2.6 on 2022-07-31 13:06

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeaderLogo', models.ImageField(help_text='Please we recommended dimensions: , 20 KB MAX', upload_to='logo/', validators=[settings.models.validate_image])),
                ('footerLogo', models.ImageField(help_text='Please we recommended dimensions: , 10 KB MAX', upload_to='logo/', validators=[settings.models.validates_image])),
            ],
        ),
    ]
