# Generated by Django 3.2.6 on 2022-07-31 13:27

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='HeaderLogo',
            field=models.ImageField(help_text='Please we recommended dimensions: , 10 KB MAX', upload_to='logo/', validators=[settings.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='websitelogo',
            name='footerLogo',
            field=models.ImageField(help_text='Please we recommended dimensions: , 20 KB MAX', upload_to='logo/', validators=[settings.models.validates_image]),
        ),
    ]
