# Generated by Django 3.2.6 on 2022-07-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20220731_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelogo',
            name='Logoname1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='websitelogo',
            name='Logoname2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
