# Generated by Django 3.2.6 on 2022-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_allorders_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorders',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
