# Generated by Django 3.2.6 on 2022-07-29 05:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0005_singup_block'),
        ('Products', '0003_allorders_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelAllOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('paid', models.BooleanField(default=False)),
                ('gst', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('shipping', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('order_id', models.CharField(default=uuid.uuid4, editable=False, max_length=250)),
                ('payment_mood', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_login.singup')),
            ],
        ),
    ]
