# Generated by Django 3.2.6 on 2022-07-29 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_cancelallorders_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelallorders',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20),
        ),
    ]
