# Generated by Django 3.2.6 on 2022-07-29 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_cancelallorders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelallorders',
            name='reson_cancel',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='allorders',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20),
        ),
    ]
