# Generated by Django 3.2.6 on 2022-07-29 11:39

import Products.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0005_singup_block'),
        ('Products', '0008_auto_20220729_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnordersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('producttotal', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='orderitem/')),
                ('size', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('cancelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.cancelallorders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.addproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnAllOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('paid', models.BooleanField(default=False)),
                ('gst', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('shipping', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('order_id', models.CharField(default=uuid.uuid4, editable=False, max_length=20)),
                ('payment_mood', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('reson_cancel', models.CharField(default=None, max_length=250, null=True)),
                ('cancelproductImage', models.ImageField(upload_to='return_orderimage/', validators=[Products.models.validate_image])),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_login.singup')),
            ],
        ),
    ]
