# Generated by Django 3.2.6 on 2022-07-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_returnallorders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnallorders',
            name='Pickup_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnallorders',
            name='Return_Confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnallorders',
            name='payment_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
