# Generated by Django 3.2.6 on 2022-07-29 13:10

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_returnordersitem_cancelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnallorders',
            name='cancelproductImage',
            field=models.ImageField(upload_to='orderitem/', validators=[Products.models.validate_image]),
        ),
    ]
