# Generated by Django 3.2.6 on 2022-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_alter_returnallorders_cancelproductimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnallorders',
            name='cancelproductImage',
            field=models.ImageField(upload_to='orderitem/'),
        ),
    ]
