# Generated by Django 3.2.6 on 2022-07-31 14:07

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_alter_returnallorders_cancelproductimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeaderLogo', models.ImageField(help_text='Please we recommended dimensions: , 10 KB MAX', upload_to='logo/', validators=[Products.models.validate_image])),
                ('footerLogo', models.ImageField(help_text='Please we recommended dimensions: , 20 KB MAX', upload_to='logo/', validators=[Products.models.validates_image])),
            ],
        ),
    ]
