# Generated by Django 3.2.6 on 2022-07-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_websitelogo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteLogo',
            new_name='WebsiteLogos',
        ),
    ]
