# Generated by Django 3.2.6 on 2022-07-31 14:16

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_rename_websitelogo_websitelogos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogos',
            name='HeaderLogo',
            field=models.ImageField(help_text='Please we recommended dimensions: , 10 KB MAX', upload_to='logo/', validators=[Products.models.validates_image]),
        ),
        migrations.AlterField(
            model_name='websitelogos',
            name='footerLogo',
            field=models.ImageField(help_text='Please we recommended dimensions: , 20 KB MAX', upload_to='logo/', validators=[Products.models.validates20_image]),
        ),
    ]
