# Generated by Django 3.2.6 on 2022-07-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_auto_20220731_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelogos',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
