# Generated by Django 3.2.6 on 2022-08-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_coupon_couponsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelallorders',
            name='payment_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
